In [1]:
import numpy as np

In [6]:
# Ex 2 - Transpose

def tp(A):
    return A.T

In [7]:
A = np.array([[3,1,1],[1,1,1]])
tp(A)

array([[3, 1],
       [1, 1],
       [1, 1]])

In [8]:
# 2.3 - Shapes

In [15]:
# 2.3-a
c = np.array([[1],[2],[3],[4]])
(c*c).shape

(4, 1)

In [17]:
#2.3-b 
np.dot(c,c)

ValueError: shapes (4,1) and (4,1) not aligned: 1 (dim 1) != 4 (dim 0)

In [20]:
# 2.3-c
np.dot(np.transpose(c), c).shape


(1, 1)

In [24]:
# Ex 2.3 E
A = np.array([[1,2],[2,3],[3,3],[4,4]])
B = np.array([[1,2,1],[2,3,2],[3,3,3],[4,4,4]])
A.shape, B.shape

((4, 2), (4, 3))

In [26]:
np.dot(A.T, B).shape

(2, 3)

In [28]:
# 2.3f
D = np.array([1,2,3])
D.shape

(3,)

In [36]:
print(A[:,1],"......shape:", A[:,1].shape)

[2 3 3 4] ......shape: (4,)


In [38]:
print(A[:, 1:2], "......Shape:", A[:, 1:2].shape)

[[2]
 [3]
 [3]
 [4]] ......Shape: (4, 1)


In [22]:
# Ex 2.4
def rv(value_list):
    return np.matrix(value_list)
value_list = [1,2,3,4,5]
rvector = rv(value_list)
cvector = rvector.T
cvector

matrix([[1],
        [2],
        [3],
        [4],
        [5]])

In [35]:
len = np.sqrt((np.array(cvector)**2).sum())

In [40]:
# Ex 2.5
np.array(cvector) / len

array([[0.13483997],
       [0.26967994],
       [0.40451992],
       [0.53935989],
       [0.67419986]])

In [41]:
# Ex 2.8
array = np.array([[1,2],[3,4]])
array

array([[1, 2],
       [3, 4]])

In [63]:
(array[:,[-1]]).tolist()

[[2], [4]]

In [65]:
# Ex 2.9 - create a numpy 2D below:
'''
Weight, height
150, 5.8
130, 5.5
120, 5.3
'''
data = np.array([[150, 5.8],
                [130, 5.5],
                [120, 5.3]])
data

array([[150. ,   5.8],
       [130. ,   5.5],
       [120. ,   5.3]])

In [72]:
data[:,[0]]+data[:,[1]]

array([[155.8],
       [135.5],
       [125.3]])