In [1]:
import numpy as np

In [2]:
# Exercise 1. about error:
# example
x = np.array([[1,-1], [0,1], [-1.5, -1]]).T
y = np.array([[1], [-1], [1]])
th = np.array([[0,0]]).T

In [3]:
y * np.dot(th.T,x) > 0 # this represent an error by 3.1 document definition

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [4]:
# theta renew until the correct value: (dot(th,x > 0))
th_new = th + y[0]*x[:,0]

In [5]:
th_new

array([[ 1., -1.],
       [ 1., -1.]])

In [6]:
# Question 1
x = np.array([[1,-1], [0,1], [-1.5, -1]]).T
y = np.array([[1], [-1], [1]])
th = np.array([0,0]).T
error = 0
for i in range(0,3):
    test = True
    while (test==True):
        if (y[i]*(np.dot(th.T,x[:,i]))) <= 0:
            th = th + (y[i]*x[:,i])
            error = error + 1
            print(i)
            print(th)
            print(error)
        else:
            test = False
            print("b")
print(f"Número de erros = {error}")

0
[ 1. -1.]
1
b
b
2
[-0.5 -2. ]
2
b
Número de erros = 2


In [7]:
# Question 1.1 c
x = np.array([[0, 1], [-1.5, -1], [1, -1]]).T
y = np.array([[-1],[1], [1]])
th = np.array([0,0]).T
error = 0
for i in range(0,3):
    test = True
    while (test==True):
        if (y[i]*(np.dot(th.T,x[:,i]))) <= 0:
            th = th + (y[i]*x[:,i])
            error = error + 1
            print(i)
            print(th)
            print(error)
        else:
            test = False
            print("b")
print(f"Número de erros = {error}")

0
[ 0. -1.]
1
b
b
b
Número de erros = 1


In [8]:
# Question 1.2a
x = np.array([[0,1], [-10, -1],[1,-1]]).T
y = np.array([[-1], [1], [1]])
th = np.array([0,0]).T
error = 0
for i in range(0,3):
    test = True
    while (test==True):
        if (y[i]*(np.dot(th.T,x[:,i]))) <= 0:
            th = th + (y[i]*x[:,i])
            error = error + 1
            print(i)
            print(th)
            print(error)
        else:
            test = False
            print("stop")
print(f"Número de erros = {error}")

0
[ 0 -1]
1
stop
stop
stop
Número de erros = 1


In [9]:
# Exercicio 2 - inicialização

In [10]:
# Question 2.1
x = np.array([[0,1], [-10, -1],[1,-1]]).T
y = np.array([[-1], [1], [1]])
th = np.array([1000,-1000]).T
error = 0
for i in range(0,3):
    test = True
    while (test==True):
        if (y[i]*(np.dot(th.T,x[:,i]))) <= 0:
            th = th + (y[i]*x[:,i])
            error = error + 1
            print(i)
            print(th)
            print(error)
        else:
            test = False
            print("stop")
print(f"Número de erros = {error}")

stop
1
[  990 -1001]
1
1
[  980 -1002]
2
1
[  970 -1003]
3
1
[  960 -1004]
4
1
[  950 -1005]
5
1
[  940 -1006]
6
1
[  930 -1007]
7
1
[  920 -1008]
8
1
[  910 -1009]
9
1
[  900 -1010]
10
1
[  890 -1011]
11
1
[  880 -1012]
12
1
[  870 -1013]
13
1
[  860 -1014]
14
1
[  850 -1015]
15
1
[  840 -1016]
16
1
[  830 -1017]
17
1
[  820 -1018]
18
1
[  810 -1019]
19
1
[  800 -1020]
20
1
[  790 -1021]
21
1
[  780 -1022]
22
1
[  770 -1023]
23
1
[  760 -1024]
24
1
[  750 -1025]
25
1
[  740 -1026]
26
1
[  730 -1027]
27
1
[  720 -1028]
28
1
[  710 -1029]
29
1
[  700 -1030]
30
1
[  690 -1031]
31
1
[  680 -1032]
32
1
[  670 -1033]
33
1
[  660 -1034]
34
1
[  650 -1035]
35
1
[  640 -1036]
36
1
[  630 -1037]
37
1
[  620 -1038]
38
1
[  610 -1039]
39
1
[  600 -1040]
40
1
[  590 -1041]
41
1
[  580 -1042]
42
1
[  570 -1043]
43
1
[  560 -1044]
44
1
[  550 -1045]
45
1
[  540 -1046]
46
1
[  530 -1047]
47
1
[  520 -1048]
48
1
[  510 -1049]
49
1
[  500 -1050]
50
1
[  490 -1051]
51
1
[  480 -1052]
52
1
[  470 -1053]


In [11]:
# Q 2.2
x = np.array([[1,-1], [0,1], [-1.5, -1]]).T
y = np.array([[1], [-1], [1]])
th = np.array([1,1]).T
error = 0
for i in range(0,3):
    test = True
    while (test==True):
        if (y[i]*(np.dot(th.T,x[:,i]))) <= 0:
            th = th + (y[i]*x[:,i])
            error = error + 1
            print(i)
            print(th)
            print(error)
        else:
            test = False
            print("b")
print(f"Número de erros = {error}")

0
[2. 0.]
1
b
1
[ 2. -1.]
2
b
2
[ 0.5 -2. ]
3
b
Número de erros = 3


In [12]:
# 3 Dual View

In [14]:
# Q 3-1
x = np.array([[-3,2], [-1,1], [-1,-1], [2,2], [1,-1]]).T
y = np.array([[1], [-1], [-1], [-1], [-1]])
th_0 = np.array([[0]])
th = np.array([0,0]).T
error = 0

for i in range(0,5):
    test = True
    while (test==True):
        print(f"theta: {th}")
        print(f"x: {x[:,i]}")
        if (y[i]*(np.dot(th.T,x[:,i]) + th_0)) <= 0:
            th = th + (y[i] * x[:,i])
            print(f"x: {x[:,i]}")
            th_0 = th_0 + y[i]
            error = error + 1
            print(f"i: {i}")
            print(f"th: {th}")
            print(f"error: {error}")
        else:
            test = False
            print("stop")
print(f"Número de erros = {error}")

theta: [0 0]
x: [-3  2]
x: [-3  2]
i: 0
th: [-3  2]
error: 1
theta: [-3  2]
x: [-3  2]
stop
theta: [-3  2]
x: [-1  1]
x: [-1  1]
i: 1
th: [-2  1]
error: 2
theta: [-2  1]
x: [-1  1]
x: [-1  1]
i: 1
th: [-1  0]
error: 3
theta: [-1  0]
x: [-1  1]
x: [-1  1]
i: 1
th: [ 0 -1]
error: 4
theta: [ 0 -1]
x: [-1  1]
stop
theta: [ 0 -1]
x: [-1 -1]
stop
theta: [ 0 -1]
x: [2 2]
stop
theta: [ 0 -1]
x: [ 1 -1]
stop
Número de erros = 4


In [27]:
# Q 3.2 - theta_0 
x = np.array([[-3,2], [-1,1], [-1,-1], [2,2], [1,-1]]).T
y = np.array([[1], [-1], [-1], [-1], [-1]])
error = np.array([[2],[4],[2],[1],[0]])
th_0 = 0

for i in range(0,5):
    th_0 = th_0+y[i]*error[i]
print(th_0)


[-5]


In [29]:
# Q 4.1.b
x = np.array[[(0,0,0),(0,0,1),(0,1,0),(0,1,1),(1,0,0),(1,0,1),(1,1,0),(1,1,1)]]
# true aswer is none

TypeError: 'builtin_function_or_method' object is not subscriptable

In [30]:
x

array([[-3, -1, -1,  2,  1],
       [ 2,  1, -1,  2, -1]])

In [68]:
# Q 4.1C
x = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]).T
th = np.array([[1,1,1]])
th_0 = (np.dot(th, x))
th_0

array([[0, 1, 1, 2, 1, 2, 2, 3]])

In [69]:
np.linalg.norm(th_0)

4.898979485566356

In [70]:
x = np.array([[-1,1], [1,-1], [1,1], [2,2]]).T
y = np.array([[1], [1], [-1], [-1]])
th_0 = np.array([[0]])
th = np.array([0,0]).T
error = 0

for i in range(0,4):
    test = True
    while (test==True):
        print(f"theta: {th}")
        print(f"x: {x[:,i]}")
        if (y[i]*(np.dot(th.T,x[:,i]) + th_0)) <= 0:
            th = th + (y[i] * x[:,i])
            print(f"x: {x[:,i]}")
            th_0 = th_0 + y[i]
            error = error + 1
            print(f"i: {i}")
            print(f"th: {th}")
            print(f"error: {error}")
        else:
            test = False
            print("stop")
print(f"Número de erros = {error}")

theta: [0 0]
x: [-1  1]
x: [-1  1]
i: 0
th: [-1  1]
error: 1
theta: [-1  1]
x: [-1  1]
stop
theta: [-1  1]
x: [ 1 -1]
x: [ 1 -1]
i: 1
th: [0 0]
error: 2
theta: [0 0]
x: [ 1 -1]
stop
theta: [0 0]
x: [1 1]
x: [1 1]
i: 2
th: [-1 -1]
error: 3
theta: [-1 -1]
x: [1 1]
stop
theta: [-1 -1]
x: [2 2]
stop
Número de erros = 3


In [71]:
th, th_0

(array([-1, -1]), array([[1]]))