In [1]:
import numpy as np

In [2]:
# 1.2 - Code distance, x, theta, theta_0
x = np.array([[1,3,5,2]]).T
th = np.array([[5,4,7,2]]).T
th0 = 5

In [3]:
distance = ((np.dot(th.T ,x)+th0) / np.linalg.norm(th))

In [4]:
distance.shape

(1, 1)

In [5]:
# 1.3 classification - side of hyperplane
def classification(distance):
    if distance > 0:
        return np.array([[1]])
    elif distance == 0:
        return np.array([[0]])
    else:
        return np.array([[-1]])
print(classification(distance))

[[1]]


In [6]:
# Ex 1.4 --- 1
# definition of A as label 1 or 0 or -1 for each data point on a plane [0,0] -2
data = np.transpose(np.array([[1, 2], [1, 3], [2, 1], [1, -1], [2, -1]]))
th = np.array([[1, 1]]).T
th0 = -2

In [7]:
distance = ((np.dot(th.T ,data)+th0) / np.linalg.norm(th))
distance

array([[ 0.70710678,  1.41421356,  0.70710678, -1.41421356, -0.70710678]])

In [8]:
classification_data = []
for i in range(0,5):
     classification_data.append(classification(distance[0][i]))
# convert to 1,5 array
predict_data = np.array(classification_data).reshape(1,5)

In [9]:
predict_data

array([[ 1,  1,  1, -1, -1]])

In [10]:
# EX 1.4 - 2. Compare predicted wtih labels
labels = np.array([[-1, -1, 1, 1, 1]])

In [11]:
evaluation = predict_data == labels
evaluation

array([[False, False,  True, False, False]])

In [12]:
score = evaluation.sum() # Consider only the true values
score
### in this case its ok for 1/5 from data

1

In [13]:
# Ex 1.6 - Whats the best separator (model) ?

In [43]:
data = np.transpose(np.array([[1, 2], [1, 3], [2, 1], [1, -1], [2, -1]]))
th = np.array([[1, 1],[2,2],[3,3],[1,2], [10,5]]).T
th0 = np.array([[-2,2,0,3,-2]])
labels = np.array([[-1, -1, 1, 1, 1]])

In [44]:
score = []
for i in range(0, th0.shape[1]):
    distance = ((np.dot(th[:,i].T ,data)+th0[0][i]) / np.linalg.norm(th[:,i]))
    classification_data = []
    for j in range(0,distance.shape[0]):
         classification_data.append(classification(distance[j]))
    predict_data = np.array(classification_data).reshape(1,5)
    evaluation = predict_data == labels
    score.append(evaluation.sum())
score = np.array([score])
print(score)

[[1 3 2 3 3]]


In [45]:
#### create a score array, select the hiscore index and select the index theta and theta_0

In [107]:
# index of best score from 4 models on numpy array
# apply this index to select the correct theta, theta_0 plane.
best_model = np.array([[[th[:,score.argmax()][0]],[th[:,score.argmax()][1]]], 
                  [[th0[0][score.argmax()]]]]).tolist()
best_model

[[[2], [2]], [[2]]]